---
# AurionOS Calamares — Display Manager configuration

displaymanagers:
  - greetd

defaultDesktopEnvironment:
    executable: "/usr/local/bin/aurion-session"
    desktopFile: "aurion"

basicSetup: false
