---
# AurionOS Calamares — Partition module configuration
# Default: Btrfs with subvolumes for snapshot support

defaultFileSystemType: "btrfs"

efiSystemPartition: "/boot/efi"
efiSystemPartitionSize: 512M

userSwapChoices:
    - none
    - small
    - file

drawNestedPartitions: false
alwaysShowPartitionLabels: true

initialPartitioningChoice: erase
initialSwapChoice: file

defaultPartitionTableType: gpt
