---
# AurionOS Calamares — Users module

defaultGroups:
    - name: users
      must_exist: false
      system: false
    - name: sudo
      must_exist: false
      system: false
    - name: video
      must_exist: false
      system: false
    - name: audio
      must_exist: false
      system: false
    - name: input
      must_exist: false
      system: false

autologinGroup: autologin

setRootPassword: false
doAutologin: false

passwordRequirements:
    nonempty: true
    minLength: 4
    maxLength: -1
