---
# AurionOS Calamares — Welcome module

showSupportUrl: true
showKnownIssuesUrl: true
showReleaseNotesUrl: false

requirements:
    requiredStorage: 15
    requiredRam: 2.0
    internetCheckUrl: https://aurion-os.dev
    check:
        - storage
        - ram
        - root
    required:
        - storage
        - ram
        - root
