---
# AurionOS Calamares — Main Configuration
# This defines how Calamares behaves during the install process.

modules-search: [ local, /usr/lib/calamares/modules ]

sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - summary
  - exec:
    - partition
    - mount
    - unpackfs
    - machineid
    - fstab
    - locale
    - keyboard
    - localecfg
    - users
    - displaymanager
    - networkcfg
    - hwclock
    - grubcfg
    - bootloader
    - postcfg
    - umount
  - show:
    - finished

branding: aurion

prompt-install: true
dont-chroot: false
disable-cancel: false
disable-cancel-during-exec: true

oem-setup: false
